### ISSUE TITLE
Bullet not logging / running

### ISSUE THREAD

**Issue by dcdieci** [flyerhzm/bullet#172]
Hi, I just set up bullet in order to analyze queries but I dont see any log statements.
I am running rails 4.0.3 with postgres. In development.rb I have the following config:
  config.after_initialize do
    Bullet.enable = true
    Bullet.alert = true
    Bullet.bullet_logger = true
    Bullet.console = true
    Bullet.growl = false
    Bullet.rails_logger = true
    Bullet.bugsnag = false
    Bullet.airbrake = false
    Bullet.add_footer = true
  end

Any ideas whats wrong ? Thanks in advance

**Comment by kevinhq** [comment]
Just in case someone else stumbled into this discussion.

I had exactly same problem. 
If you want to see Bullet logs something, just remove any of your eager load codes, and you will see it working.

Maybe, it's good idea to inform if everything is working well, instead of just leaving the log empty so we know that Bullet is running but the whole codes are fine ( no problem detected ) ?
